services:

  eureka-server:
    image: gebozhinov/eureka-server:latest
    pull_policy: always
    container_name: eureka-server
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - app-network

  user-service:
    image: gebozhinov/user-service:latest
    pull_policy: always
    container_name: user-service
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/user_service
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_ISSUER_URL: http://keycloak:8080/realms/local-realm
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      AUTHENTICATION_SERVICE_URL: http://AUTHENTICATION-SERVICE
    ports:
      - "8088:8081"
    depends_on:
      - eureka-server
    networks:
      - app-network

  authentication-service:
    image: gebozhinov/authentication-service:latest
    pull_policy: always
    container_name: authentication-service
    restart: unless-stopped
    environment:
      JWT_ISSUER_URL: http://keycloak:8080/realms/local-realm
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_SECRET: aKeDLv7Uht8EI5pZkfUZQAg0gEHdkAQc
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    ports:
      - "8089:8082"
    depends_on:
      - eureka-server
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app-network